name: 'Action check status sd jira'
description: 'service desk status check'
inputs:  
  url-jira:
    description: 'url jira'
    required: true
  basic-auth:
    description: 'jira authentication'
    required: true
  other-types-current-status:
    description: 'other types of current status'
    required: true
outputs:
  result:
    description: 'finished process'
runs:
  using: 'node12'
  main: 'dist/index.js'